const data = {
    products: [
        {
            _id: '1',
            name: 'Nykaa Naturals Skin Potion Anti- Ageing Skincare Face Oil',
            category: 'skin care',
            image: '/images/sk2.jpg',
            feature:'offer',
            price: 499,
            countInStock: 10,
            brand: 'Nykaa',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '2',
            name: 'Nykaa Clay It Cool Daily Detox Clay Mask',
            category: 'skin care',
            image: '/images/sk1.jpg',
            feature:'offer',
            price: 510,
            countInStock: 20,
            brand: 'Nykaa',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '3',
            name: 'Nykaa Clay It Cool Pore Perfect Clay Mask',
            category: 'Skin care',
            image: '/images/sk3.jpg',
             feature:'BESTSELLER',
            price: 320,
            countInStock: 10,
            brand: 'Nykaa',
            rating: 4.8,
            numReviews: 17,
            description: 'high quality product',
        },
        {
            _id: '4',
            name: 'Nykaa Coconut & Shea Butter Hand & Nail Crème',
            category: 'skin care',
            image: '/images/sk4.jpg',
             feature:'offer',
            price: 280,
            countInStock: 15,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 14,
            description: 'high quality product',
        },
        {
            _id: '5',
            name: 'Nykaa Naturals Tea Tree & Neem Purifying & Hydrating Gel',
            category: 'skin care',
            image: '/images/sk5.jpg',
             feature:'BESTSELLER',
            price: 665,
            countInStock: 5,
            brand: 'Nykaa',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Nykaa Wanderlust Body Lotion',
            category: 'skin care',
            image: '/images/sk6.jpg',
            feature:'offer',
            price: 339,
            countInStock: 3200,
            brand: 'Nykaa',
            rating: 4.5,
            numReviews: 15,
            description: 'high quality product',
        },
    ],
};
module.exports=data;