export const combinedata = {
    products: [
        {
            _id: '1',
            name: 'Aqualogica Hydrate+ Gel Face Moisturizer',
            category: 'Combine',
            image: '/images/cp1.jpg',
            price: 599,
            countInStock: 10,
            brand: 'Aqualogica',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '2',
            name: 'Aqualogica Hydrate+ Face Serum',
            category: 'Combine',
            image: '/images/cp2.jpg',
            price: 510,
            countInStock: 20,
            brand: 'Aqualogica',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '3',
            name: 'Aqualogica Hydrate+ Sunscreen',
            category: 'Combine',
            image: '/images/cp3.jpg',
            price: 340,
            countInStock: 10,
            brand: 'Aqualogica',
            rating: 4.8,
            numReviews: 17,
            description: 'high quality product',
        },
        {
            _id: '4',
            name: 'Nykaa Wanderlust Mediterranean Sea Salt Shower Gel, Body Lotion & Body Scrub Combo',
            category: 'Combine',
            image: '/images/cp4.jpg',
            price: 650,
            countInStock: 15,
            brand: 'Wanderlust',
            rating: 4.5,
            numReviews: 14,
            description: 'high quality product',
        },
        {
            _id: '5',
            name: 'Nykaa At Home Mani Pedi Cherry Blossom Shower Gel + Body Scrub + Body Lotion Combo',
            category: 'Combine',
            image: '/images/cp5.jpg',
            price: 865,
            countInStock: 5,
            brand: 'Wanderlust',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Nykaa Wanderlust Shower Gel - Mediterranean Sea Salt',
            category: 'Combine',
            image: '/images/cp6.jpg',
            price: 650,
            countInStock: 3200,
            brand: 'Wanderlust',
            rating: 4.2,
            numReviews: 15,
            description: 'high quality product',
        },
        {
            _id: '7',
            name: 'Clinique Even Better Clinical Radical Dark Spot Corrector + Interrupter Mini ',
            category: 'Combine',
            image: '/images/cp7.jpg',
            price: 1350,
            countInStock: 200,
            brand: 'Clinique',
            rating: 4.5,
            numReviews: 15,
            description: 'high quality product',
        },
        {
            _id: '8',
            name: 'Lime Crime Wet Cherry Lip Gloss - Disco Cherry',
            category: 'Combine',
            image: '/images/cp8.jpg',
            price: 1250,
            countInStock: 3200,
            brand: 'Lime Crime',
            rating: 4.3,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '9',
            name: 'Kama Ayurveda De-tan & Cleanse Mini Duo',
            category: 'Combine',
            image: '/images/cp9.jpg',
            price: 1599,
            countInStock: 10,
            brand: 'Kama Ayurveda',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '10',
            name: 'Lakme Absolute Illuminating Blush Shimmer Brick - In Pink + Absolute Highlighter - Moon-Lit Combo',
            category: 'Combine',
            image: '/images/cp10.jpg',
            price: 1610,
            countInStock: 20,
            brand: 'Lakme',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '11',
            name: 'Clinique Better, Brighter Skin Set',
            category: 'Combine',
            image: '/images/cp11.jpg',
            price: 4040,
            countInStock: 30,
            brand: 'Clinique',
            rating: 4.8,
            numReviews: 17,
            description: 'high quality product',
        },
        {
            _id: '12',
            name: 'Kama Ayurveda Am : Pm Hydration Mini Duo',
            category: 'Combine',
            image: '/images/cp12.jpg',
            price: 1650,
            countInStock: 215,
            brand: 'Kama Ayurveda',
            rating: 4.5,
            numReviews: 14,
            description: 'high quality product',
        },
        {
            _id: '13',
            name: 'Nykaa So Creme! Creamy Matte Lipstick - Wakeup Makeup',
            category: 'Combine',
            image: '/images/cp13.jpg',
            price: 265,
            countInStock: 52,
            brand: 'Nykaa',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '14',
            name: 'Lime Crime Velvetines Liquid Matte Lipstick - Feelins',
            category: 'Combine',
            image: '/images/cp14.jpg',
            price: 1250,
            countInStock: 300,
            brand: 'Lime Crime',
            rating: 4.2,
            numReviews: 15,
            description: 'high quality product',
        },
        {
            _id: '15',
            name: 'LOreal Paris Pure Clay Mask Detoxify',
            category: 'Combine',
            image: '/images/cp15.jpg',
            price: 1350,
            countInStock: 100,
            brand: 'LOreal',
            rating: 4.5,
            numReviews: 15,
            description: 'high quality product',
        },
        {
            _id: '16',
            name: 'LOreal Paris Rouge Signature Matte Liquid Lipstick - 151 I Insist',
            category: 'Combine',
            image: '/images/cp16.jpg',
            price: 1250,
            countInStock: 200,
            brand: 'LOreal',
            rating: 4.3,
            numReviews: 10,
            description: 'high quality product',
        },
    ],
};