export const data1 = {
    products: [
        {
            _id: '1',
            name: 'Plum Glow Boost Combo - Fights Acne, Hyperpigmentation & Dark Spots',
            category: 'acne fighter',
            image: '/images/af1.jpg',
            price: 1499,
            countInStock: 10,
            brand: 'Plum',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '2',
            name: 'Plum Clear Skin Specialist Combo - Fights Acne & Clarifies Skin',
            category: 'acne fighter',
            image: '/images/af2.jpg',
            price: 1510,
            countInStock: 20,
            brand: 'Plum',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '3',
            name: 'Plum Facial Ready Green Tea Kit - Fights Acne & Exfoliate',
            category: 'acne fighter',
            image: '/images/af3.jpg',
            price: 1320,
            countInStock: 10,
            brand: 'Plum',
            rating: 4.8,
            numReviews: 17,
            description: 'high quality product',
        },
        
    ],
};
