const data =  [
        {
            _id: '1',
            name: 'Nykaa Naturals Skin Potion Anti- Ageing Skincare Face Oil',
            category: 'skin care',
            image:'/images/sk2.jpg',
            price: 499,
            countInStock: 10,
            brand: 'Nykaa',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '2',
            name: 'Nykaa Clay It Cool Daily Detox Clay Mask',
            category: 'skin care',
            image: '/images/sk1.jpg',
            feature:'offer',
            price: 510,
            countInStock: 20,
            brand: 'Nykaa',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '3',
            name: 'Nykaa Clay It Cool Pore Perfect Clay Mask',
            category: 'Skin care',
            image: '/images/sk3.jpg',
             feature:'BESTSELLER',
            price: 320,
            countInStock: 10,
            brand: 'Nykaa',
            rating: 4.8,
            numReviews: 17,
            description: 'high quality product',
        },
        {
            _id: '4',
            name: 'Nykaa Coconut & Shea Butter Hand & Nail Crème',
            category: 'skin care',
            image: '/images/sk4.jpg',
             feature:'offer',
            price: 280,
            countInStock: 15,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 14,
            description: 'high quality product',
        },
        {
            _id: '5',
            name: 'Nykaa Naturals Tea Tree & Neem Purifying & Hydrating Gel',
            category: 'skin care',
            image: '/images/sk5.jpg',
             feature:'BESTSELLER',
            price: 665,
            countInStock: 5,
            brand: 'Nykaa',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Nykaa Wanderlust Body Lotion',
            category: 'skin care',
            image: '/images/sk6.jpg',
            feature:'offer',
            price: 339,
            countInStock: 3200,
            brand: 'Nykaa',
            rating: 4.5,
            numReviews: 15,
            description: 'high quality product',
        },{
            _id: '7',
            name: 'Plum Glow Boost Combo - Fights Acne, Hyperpigmentation & Dark Spots',
            category: 'acne fighter',
            image: '/images/af1.jpg',
            price: 1499,
            countInStock: 10,
            brand: 'Plum',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '8',
            name: 'Plum Clear Skin Specialist Combo - Fights Acne & Clarifies Skin',
            category: 'acne fighter',
            image: '/images/af2.jpg',
            price: 1510,
            countInStock: 20,
            brand: 'Plum',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '9',
            name: 'Plum Facial Ready Green Tea Kit - Fights Acne & Exfoliate',
            category: 'acne fighter',
            image: '/images/af3.jpg',
            price: 1320,
            countInStock: 10,
            brand: 'Plum',
            rating: 4.8,
            numReviews: 17,
            description: 'high quality product',
        },
        {
            _id: '10',
            name: 'Dove Essentials Combo',
            category: 'Dove',
            image: '/images/d1.jpg',
            price: 799,
            countInStock: 10,
            brand: 'Dove',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '11',
            name: 'Dove Body Love Nourished Radiance Body Lotion Paraben Free',
            category: 'Dove',
            image: '/images/d2.jpg',
            price: 580,
            countInStock: 20,
            brand: 'Dove',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '12',
            name: 'Dove Original & Eventone Deodorant For Women Combo',
            category: 'Dove',
            image: '/images/d3.jpg',
            price: 1320,
            countInStock: 10,
            brand: 'Dove',
            rating: 4.8,
            numReviews: 17,
            description: 'high quality product',
        },
        {
            _id: '13',
            name: 'Dove Supple Bounce Body Lotion',
            category: 'Dove',
            image: '/images/d4.jpg',
            price: 580,
            countInStock: 15,
            brand: 'Dove',
            rating: 4.5,
            numReviews: 14,
            description: 'high quality product',
        },
        {
            _id: '14',
            name: 'Dove Healthy Ritual Strengthening Shampoo(650ml) + Hair Mask',
            category: 'Dove',
            image: '/images/d5.jpg',
            price: 665,
            countInStock: 5,
            brand: 'Dove',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '15',
            name: 'Dove Deeply Nourishing Body Wash',
            category: 'Dove',
            image: '/images/d6.jpg',
            price: 339,
            countInStock: 3200,
            brand: 'Dove',
            rating: 4.5,
            numReviews: 15,
            description: 'high quality product',
        },
        {
            _id: '16',
            name: 'Garnier Bright Complete 30X VITAMIN C Booster Face Serum',
            category: 'Garnier',
            image: '/images/g1.jpg',
            price: 799,
            countInStock: 10,
            brand: 'Garnier',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '17',
            name: 'Garnier Body Love Nourished Radiance Body Lotion Paraben Free',
            category: 'Garnier',
            image: '/images/g2.jpg',
            price: 510,
            countInStock: 20,
            brand: 'Garnier',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '18',
            name: 'Garnier Micellar Water With Vitamin C',
            category: 'Garnier',
            image: '/images/g3.jpg',
            price: 240,
            countInStock: 10,
            brand: 'Garnier',
            rating: 4.8,
            numReviews: 17,
            description: 'high quality product',
        },
        {
            _id: '19',
            name: 'Garnier Skin Naturals Face Serum Sheet Mask Pack of 10',
            category: 'Garnier',
            image: '/images/g4.jpg',
            price: 650,
            countInStock: 15,
            brand: 'Garnier',
            rating: 4.5,
            numReviews: 14,
            description: 'high quality product',
        },
        {
            _id: '20',
            name: 'Garnier Fructis Banana Combo',
            category: 'Garnier',
            image: '/images/g5.jpg',
            price: 665,
            countInStock: 5,
            brand: 'Garnier',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '21',
            name: 'Garnier Fructis Hair Food - Quenching Aloe Vera Hair Mask For Normal To Dry Hair',
            category: 'Garnier',
            image: '/images/g6.jpg',
            price: 750,
            countInStock: 3200,
            brand: 'Garnier',
            rating: 4.5,
            numReviews: 15,
            description: 'high quality product',
        },
        {
            _id: '22',
            name: 'Lakme Absolute Skin Natural Mousse Mattreal Foundation - Rick Walnut',
            category: 'Lakme',
            image: '/images/l1.jpg',
            price: 599,
            countInStock: 10,
            brand: 'Lakme',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '23',
            name: 'Lakme Absolute Liquid Highlighter - Rose Golde',
            category: 'Lakme',
            image: '/images/l2.jpg',
            price: 610,
            countInStock: 20,
            brand: 'Lakme',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '24',
            name: 'Lakme Eyeconic Curling Mascara - Black + Absolute Blur Perfect Makeup Primer Combo',
            category: 'Lakme',
            image: '/images/l3.jpg',
            price: 1040,
            countInStock: 10,
            brand: 'Lakme',
            rating: 4.8,
            numReviews: 17,
            description: 'high quality product',
        },
        {
            _id: '25',
            name: 'Lakme Absolute Matte Revolution Lip Color - 501 Dynamite Berry',
            category: 'Lakme',
            image: '/images/l4.jpg',
            price: 650,
            countInStock: 15,
            brand: 'Lakme',
            rating: 4.5,
            numReviews: 14,
            description: 'high quality product',
        },
        {
            _id: '26',
            name: 'Lakme Absolute Spotlight Eye Shadow Palette - Stilettos',
            category: 'Lakme',
            image: '/images/l5.jpg',
            price: 665,
            countInStock: 5,
            brand: 'Lakme',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '27',
            name: 'Lakme Absolute Precision Lip Paint',
            category: 'Lakme',
            image: '/images/l6.jpg',
            price: 250,
            countInStock: 3200,
            brand: 'Lakme',
            rating: 4.2,
            numReviews: 15,
            description: 'high quality product',
        },
        {
            _id: '28',
            name: 'Lakme Peach Milk Soft Creme Moisturizer',
            category: 'Lakme',
            image: '/images/l7.jpg',
            price: 1350,
            countInStock: 200,
            brand: 'Lakme',
            rating: 4.5,
            numReviews: 15,
            description: 'high quality product',
        },
        {
            _id: '29',
            name: 'Lakme Hydra Pro (Day + Night Cream) Combo',
            category: 'Lakme',
            image: '/images/l8.jpg',
            price: 250,
            countInStock: 3200,
            brand: 'Lakme',
            rating: 4.3,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '30',
            name: 'Aqualogica Hydrate+ Gel Face Moisturizer',
            category: 'Combine',
            image: '/images/cp1.jpg',
            price: 599,
            countInStock: 10,
            brand: 'Aqualogica',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '31',
            name: 'Aqualogica Hydrate+ Face Serum',
            category: 'Combine',
            image: '/images/cp2.jpg',
            price: 510,
            countInStock: 20,
            brand: 'Aqualogica',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '32',
            name: 'Aqualogica Hydrate+ Sunscreen',
            category: 'Combine',
            image: '/images/cp3.jpg',
            price: 340,
            countInStock: 10,
            brand: 'Aqualogica',
            rating: 4.8,
            numReviews: 17,
            description: 'high quality product',
        },
        {
            _id: '33',
            name: 'Nykaa Wanderlust Mediterranean Sea Salt Shower Gel, Body Lotion & Body Scrub Combo',
            category: 'Combine',
            image: '/images/cp4.jpg',
            price: 650,
            countInStock: 15,
            brand: 'Wanderlust',
            rating: 4.5,
            numReviews: 14,
            description: 'high quality product',
        },
        {
            _id: '34',
            name: 'Nykaa At Home Mani Pedi Cherry Blossom Shower Gel + Body Scrub + Body Lotion Combo',
            category: 'Combine',
            image: '/images/cp5.jpg',
            price: 865,
            countInStock: 5,
            brand: 'Wanderlust',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '35',
            name: 'Nykaa Wanderlust Shower Gel - Mediterranean Sea Salt',
            category: 'Combine',
            image: '/images/cp6.jpg',
            price: 650,
            countInStock: 3200,
            brand: 'Wanderlust',
            rating: 4.2,
            numReviews: 15,
            description: 'high quality product',
        },
        {
            _id: '36',
            name: 'Clinique Even Better Clinical Radical Dark Spot Corrector + Interrupter Mini ',
            category: 'Combine',
            image: '/images/cp7.jpg',
            price: 1350,
            countInStock: 200,
            brand: 'Clinique',
            rating: 4.5,
            numReviews: 15,
            description: 'high quality product',
        },
        {
            _id: '37',
            name: 'Lime Crime Wet Cherry Lip Gloss - Disco Cherry',
            category: 'Combine',
            image: '/images/cp8.jpg',
            price: 1250,
            countInStock: 3200,
            brand: 'Lime Crime',
            rating: 4.3,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '38',
            name: 'Kama Ayurveda De-tan & Cleanse Mini Duo',
            category: 'Combine',
            image: '/images/cp9.jpg',
            price: 1599,
            countInStock: 10,
            brand: 'Kama Ayurveda',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '39',
            name: 'Lakme Absolute Illuminating Blush Shimmer Brick - In Pink + Absolute Highlighter - Moon-Lit Combo',
            category: 'Combine',
            image: '/images/cp10.jpg',
            price: 1610,
            countInStock: 20,
            brand: 'Lakme',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '40',
            name: 'Clinique Better, Brighter Skin Set',
            category: 'Combine',
            image: '/images/cp11.jpg',
            price: 4040,
            countInStock: 30,
            brand: 'Clinique',
            rating: 4.8,
            numReviews: 17,
            description: 'high quality product',
        },
        {
            _id: '41',
            name: 'Kama Ayurveda Am : Pm Hydration Mini Duo',
            category: 'Combine',
            image: '/images/cp12.jpg',
            price: 1650,
            countInStock: 215,
            brand: 'Kama Ayurveda',
            rating: 4.5,
            numReviews: 14,
            description: 'high quality product',
        },
        {
            _id: '42',
            name: 'Nykaa So Creme! Creamy Matte Lipstick - Wakeup Makeup',
            category: 'Combine',
            image: '/images/cp13.jpg',
            price: 265,
            countInStock: 52,
            brand: 'Nykaa',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '43',
            name: 'Lime Crime Velvetines Liquid Matte Lipstick - Feelins',
            category: 'Combine',
            image: '/images/cp14.jpg',
            price: 1250,
            countInStock: 300,
            brand: 'Lime Crime',
            rating: 4.2,
            numReviews: 15,
            description: 'high quality product',
        },
        {
            _id: '44',
            name: 'LOreal Paris Pure Clay Mask Detoxify',
            category: 'Combine',
            image: '/images/cp15.jpg',
            price: 1350,
            countInStock: 100,
            brand: 'LOreal',
            rating: 4.5,
            numReviews: 15,
            description: 'high quality product',
        },
        {
            _id: '45',
            name: 'LOreal Paris Rouge Signature Matte Liquid Lipstick - 151 I Insist',
            category: 'Combine',
            image: '/images/cp16.jpg',
            price: 1250,
            countInStock: 200,
            brand: 'LOreal',
            rating: 4.3,
            numReviews: 10,
            description: 'high quality product',
        },
    ]

export default data;