export const data3 = {
    products: [
        {
            _id: '1',
            name: 'Garnier Bright Complete 30X VITAMIN C Booster Face Serum',
            category: 'Garnier',
            image: '/images/g1.jpg',
            price: 799,
            countInStock: 10,
            brand: 'Garnier',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '2',
            name: 'Garnier Body Love Nourished Radiance Body Lotion Paraben Free',
            category: 'Garnier',
            image: '/images/g2.jpg',
            price: 510,
            countInStock: 20,
            brand: 'Garnier',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '3',
            name: 'Garnier Micellar Water With Vitamin C',
            category: 'Garnier',
            image: '/images/g3.jpg',
            price: 240,
            countInStock: 10,
            brand: 'Garnier',
            rating: 4.8,
            numReviews: 17,
            description: 'high quality product',
        },
        {
            _id: '4',
            name: 'Garnier Skin Naturals Face Serum Sheet Mask Pack of 10',
            category: 'Garnier',
            image: '/images/g4.jpg',
            price: 650,
            countInStock: 15,
            brand: 'Garnier',
            rating: 4.5,
            numReviews: 14,
            description: 'high quality product',
        },
        {
            _id: '5',
            name: 'Garnier Fructis Banana Combo',
            category: 'Garnier',
            image: '/images/g5.jpg',
            price: 665,
            countInStock: 5,
            brand: 'Garnier',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Garnier Fructis Hair Food - Quenching Aloe Vera Hair Mask For Normal To Dry Hair',
            category: 'Garnier',
            image: '/images/g6.jpg',
            price: 750,
            countInStock: 3200,
            brand: 'Garnier',
            rating: 4.5,
            numReviews: 15,
            description: 'high quality product',
        },
    ],
};
