export const data4 = {
    products: [
        {
            _id: '1',
            name: 'Lakme Absolute Skin Natural Mousse Mattreal Foundation - Rick Walnut',
            category: 'Lakme',
            image: '/images/l1.jpg',
            price: 599,
            countInStock: 10,
            brand: 'Lakme',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '2',
            name: 'Lakme Absolute Liquid Highlighter - Rose Golde',
            category: 'Lakme',
            image: '/images/l2.jpg',
            price: 610,
            countInStock: 20,
            brand: 'Lakme',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '3',
            name: 'Lakme Eyeconic Curling Mascara - Black + Absolute Blur Perfect Makeup Primer Combo',
            category: 'Lakme',
            image: '/images/l3.jpg',
            price: 1040,
            countInStock: 10,
            brand: 'Lakme',
            rating: 4.8,
            numReviews: 17,
            description: 'high quality product',
        },
        {
            _id: '4',
            name: 'Lakme Absolute Matte Revolution Lip Color - 501 Dynamite Berry',
            category: 'Lakme',
            image: '/images/l4.jpg',
            price: 650,
            countInStock: 15,
            brand: 'Lakme',
            rating: 4.5,
            numReviews: 14,
            description: 'high quality product',
        },
        {
            _id: '5',
            name: 'Lakme Absolute Spotlight Eye Shadow Palette - Stilettos',
            category: 'Lakme',
            image: '/images/l5.jpg',
            price: 665,
            countInStock: 5,
            brand: 'Lakme',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Lakme Absolute Precision Lip Paint',
            category: 'Lakme',
            image: '/images/l6.jpg',
            price: 250,
            countInStock: 3200,
            brand: 'Lakme',
            rating: 4.2,
            numReviews: 15,
            description: 'high quality product',
        },
        {
            _id: '7',
            name: 'Lakme Peach Milk Soft Creme Moisturizer',
            category: 'Lakme',
            image: '/images/l7.jpg',
            price: 1350,
            countInStock: 200,
            brand: 'Lakme',
            rating: 4.5,
            numReviews: 15,
            description: 'high quality product',
        },
        {
            _id: '8',
            name: 'Lakme Hydra Pro (Day + Night Cream) Combo',
            category: 'Lakme',
            image: '/images/l8.jpg',
            price: 250,
            countInStock: 3200,
            brand: 'Lakme',
            rating: 4.3,
            numReviews: 10,
            description: 'high quality product',
        },
    ],
};