export const data2 = {
    products: [
        {
            _id: '1',
            name: 'Dove Essentials Combo',
            category: 'Dove',
            image: '/images/d1.jpg',
            price: 799,
            countInStock: 10,
            brand: 'Dove',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '2',
            name: 'Dove Body Love Nourished Radiance Body Lotion Paraben Free',
            category: 'Dove',
            image: '/images/d2.jpg',
            price: 580,
            countInStock: 20,
            brand: 'Dove',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '3',
            name: 'Dove Original & Eventone Deodorant For Women Combo',
            category: 'Dove',
            image: '/images/d3.jpg',
            price: 1320,
            countInStock: 10,
            brand: 'Dove',
            rating: 4.8,
            numReviews: 17,
            description: 'high quality product',
        },
        {
            _id: '4',
            name: 'Dove Supple Bounce Body Lotion',
            category: 'Dove',
            image: '/images/d4.jpg',
            price: 580,
            countInStock: 15,
            brand: 'Dove',
            rating: 4.5,
            numReviews: 14,
            description: 'high quality product',
        },
        {
            _id: '5',
            name: 'Dove Healthy Ritual Strengthening Shampoo(650ml) + Hair Mask',
            category: 'Dove',
            image: '/images/d5.jpg',
            price: 665,
            countInStock: 5,
            brand: 'Dove',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Dove Deeply Nourishing Body Wash',
            category: 'Dove',
            image: '/images/d6.jpg',
            price: 339,
            countInStock: 3200,
            brand: 'Dove',
            rating: 4.5,
            numReviews: 15,
            description: 'high quality product',
        },
    ],
};
